// src/App.tsx
import { useState } from "react";
import { invoke } from "@tauri-apps/api/tauri";

function App() {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
    setGreetMsg(await invoke("greet", { name }));
  }

  return (
    <div className="container">
      <h1>Welcome to Tauri!</h1>
      <div className="row">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            greet();
          }}
        >
          <input
            id="greet-input"
            onChange={(e) => setName(e.currentTarget.value)}
            placeholder="Enter a name..."
          />
          <button type="submit">Greet</button>
        </form>
      </div>
      <p>{greetMsg}</p>
    </div>
  );
}

export default App;

// src/app/app.component.ts
import { Component } from "@angular/core";
import { invoke } from "@tauri-apps/api/tauri";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styles: [],
})
export class AppComponent {
  greetingMessage = "";

  addNote(event: SubmitEvent, title: string, body: string): void {
    event.preventDefault();

    invoke<string>("add_note", { title, body }).then((text) => {
      console.log(text);
    });
    invoke<string>("browse_note").then((text) => {
      console.log(text);
    });
  }
}

<div>
  <h1 class="text-center">Welcome to Tauri + Angular!</h1>
  <div>
    <form (submit)="addNote($event, noteTitle.value, noteBody.value)">
      <div class="m-2">
        <input
          #noteTitle
          placeholder="Enter a name..."
          class="input input-bordered w-full"
        />
      </div>
      <div class="m-2">
        <textarea
          #noteBody
          placeholder="Enter a body..."
          class="textarea textarea-bordered w-full h-[25rem]"
        ></textarea>
      </div>
      <div class="m-2">
        <button type="submit" class="btn btn-primary btn-outline">Greet</button>
      </div>
    </form>
  </div>
</div>
